# Generated by Django 5.2.12 on 2026-04-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_productcategory_product_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_html",
            field=models.TextField(
                blank=True,
                help_text="Безопасная разметка для витрины. Если пусто — показывается обычное описание.",
                verbose_name="Описание (HTML)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание (plain)"),
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Группа"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Параметр")),
                ("value", models.CharField(max_length=2048, verbose_name="Значение")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="api.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="Подпись варианта"),
                ),
                (
                    "wb_nm_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Артикул WB (nm)"
                    ),
                ),
                (
                    "price_from",
                    models.PositiveIntegerField(default=0, verbose_name="Цена от, ₽"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Вариант по умолчанию",
                    ),
                ),
                (
                    "marketplace_wb_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        verbose_name="Ссылка на карточку WB этого варианта",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="api.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товара",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="products/%Y/%m/",
                verbose_name="Файл на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(
                blank=True, max_length=2048, verbose_name="URL изображения (внешний)"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.productvariant",
                verbose_name="Вариант",
            ),
        ),
    ]
