# Generated by Django 5.2.12 on 2026-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_variants_specs_file_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="blog/covers/%Y/%m/",
                verbose_name="Обложка (файл)",
            ),
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="after_image_file",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="portfolio/%Y/%m/",
                verbose_name='Фото «после» (файл)',
            ),
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="before_image_file",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="portfolio/%Y/%m/",
                verbose_name='Фото «до» (файл)',
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="photo_file",
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="reviews/%Y/%m/",
                verbose_name="Фото (файл с компьютера)",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name="Или обложка по внешнему URL",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="after_image",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name='Или «после» по внешнему URL',
            ),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="before_image",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name='Или «до» по внешнему URL',
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="photo_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name="Или фото по внешнему URL",
            ),
        ),
    ]
