# Generated by Django 5.2.12 on 2026-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_price_verbose_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные главной (JSON)')),
            ],
            options={
                'verbose_name': 'Главная страница (контент)',
                'verbose_name_plural': 'Главная страница (контент)',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='г. Москва, производственная зона (адрес уточняется)', max_length=400, verbose_name='Адрес (текст)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='hello@fabric-awnings.example', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='branding/%Y/%m/', verbose_name='Фавикон (.ico или PNG)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note',
            field=models.CharField(blank=True, default='Производство и монтаж под ключ.', max_length=255, verbose_name='Подвал: текст под слоганом'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_telegram_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='Ссылка Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_vk_url',
            field=models.URLField(blank=True, max_length=512, verbose_name='Ссылка «ВКонтакте»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal',
            field=models.CharField(blank=True, default='ООО «Фабрика Тентов», ИНН 0000000000', max_length=400, verbose_name='Реквизиты (кратко)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='branding/%Y/%m/', verbose_name='Логотип (SVG, PNG, WebP)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_display',
            field=models.CharField(blank=True, default='+7 (800) 000-00-00', max_length=64, verbose_name='Телефон (как на сайте)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_href',
            field=models.CharField(blank=True, default='tel:+78000000000', max_length=64, verbose_name='Ссылка tel:'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Фабрика Тентов', max_length=120, verbose_name='Название сайта (шапка, подвал)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='Тенты на заказ для бизнеса и частных клиентов', max_length=255, verbose_name='Слоган в подвале'),
        ),
    ]
