# Generated by Django 6.0.4 on 2026-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_images_upload_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='product_photo_aspect',
            field=models.CharField(choices=[('portrait_3_4', 'Портрет 3:4 (рекомендуется 900×1200 px)'), ('square', 'Квадрат 1:1')], default='portrait_3_4', help_text='Соотношение сторон рамки каталога и карточки товара. Изображения показываются целиком, без обрезки (поля под фоном, если пропорции другие). Рекомендуемый размер файлов: 900×1200 для портрета или квадрат для режима 1:1.', max_length=32, verbose_name='Формат фото товаров на витрине'),
        ),
    ]
