# Generated by Django 6.0.4 on 2026-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sitesettings_smtp_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Implicit SSL с первого пакета. Если включено, STARTTLS отключается автоматически.', verbose_name='SSL (порт 465)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Для порта 587. Не включайте вместе с «SSL (465)» — при обоих флажках используется только SSL.', verbose_name='TLS (STARTTLS)'),
        ),
    ]
