# Generated by Django 6.0.4 on 2026-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_homepage_ps_icon_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_api_key',
            field=models.CharField(blank=True, default='', help_text='Из панели приложения в Битрикс24. Не публикуйте в открытых репозиториях.', max_length=256, verbose_name='API-ключ Astrum (X-API-Key)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_api_url',
            field=models.URLField(default='https://app-5.astrum.agency/api/order', help_text='Обычно не меняйте, если провайдер не дал другой адрес.', max_length=512, verbose_name='URL endpoint заказа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_assigned_default',
            field=models.PositiveIntegerField(blank=True, help_text='Числовой ID пользователя Bitrix24. Обязателен при включённой интеграции.', null=True, verbose_name='ID ответственного в Б24 (assigned_default)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_contact_behavior',
            field=models.CharField(choices=[('SELECT_EXISTING', 'Искать контакт по телефону/email, иначе создать'), ('CREATE_ANYWAY', 'Всегда создавать новый контакт')], default='SELECT_EXISTING', max_length=32, verbose_name='Поведение с контактами'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_deal_title_prefix',
            field=models.CharField(default='Заказ с сайта', help_text='В Б24: «{префикс} {номер заказа}», например «Заказ с сайта FAB-…».', max_length=120, verbose_name='Префикс названия сделки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_enabled',
            field=models.BooleanField(default=False, help_text='Заказы из корзины уходят в приложение «Заявки с сайта». Пока выключено — можно задать ключ из .env (ASTRUM_CRM_API_KEY).', verbose_name='Включить отправку заказов в Битрикс24 (Astrum)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_entity_behavior',
            field=models.CharField(choices=[('ADD_TO_EXISTING', 'Добавлять к активной сделке/лиду'), ('CREATE_ANYWAY', 'Всегда новая сделка/лид'), ('IGNORE_EXISTING', 'Не создавать, если уже есть активная')], default='ADD_TO_EXISTING', max_length=32, verbose_name='Поведение со сделкой/лидом'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='astrum_crm_timeout_seconds',
            field=models.PositiveSmallIntegerField(default=15, help_text='От 5 до 120. Запрос к Astrum при оформлении заказа.', verbose_name='Таймаут HTTP (сек.)'),
        ),
    ]
