# Generated by Django 6.0.4 on 2026-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_sitesettings_astrum_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bitrix_catalog_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Если заполнено и у варианта пусто — в CRM (Astrum) подставится этот ID позиции каталога вместо текста без привязки.', null=True, verbose_name='ID товара в каталоге Битрикс24'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='bitrix_catalog_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Приоритет над полем товара. ID позиции в каталоге CRM — см. документацию Astrum (product_id).', null=True, verbose_name='ID в каталоге Б24 (вариант)'),
        ),
    ]
