# Generated by Django 6.0.4 on 2026-04-13 18:53

from django.db import migrations, models


def seed_email_templates(apps, schema_editor):
    from api.email_template_defaults import DEFAULT_EMAIL_TEMPLATES

    SiteEmailTemplate = apps.get_model("api", "SiteEmailTemplate")
    for key, d in DEFAULT_EMAIL_TEMPLATES.items():
        SiteEmailTemplate.objects.get_or_create(
            key=key,
            defaults={"subject": d["subject"], "body": d["body"]},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customerprofile_password_change_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('manager_calculator', 'Менеджерам: заявка с калькулятора'), ('manager_callback', 'Менеджерам: обратный звонок'), ('manager_cart', 'Менеджерам: заказ из корзины'), ('buyer_credentials', 'Покупателю: доступ в личный кабинет'), ('smtp_test', 'Служебное: тест SMTP из админки')], max_length=64, unique=True, verbose_name='Тип письма')),
                ('subject', models.CharField(blank=True, default='', help_text='Плейсхолдеры в фигурных скобках, например {name}. Подсказка по полям — блок ниже.', max_length=998, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, default='', help_text='Текст без HTML, переносы строк сохраняются. Плейсхолдеры как в теме.', verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed_email_templates, noop_reverse),
    ]
