# Generated by Django 6.0.4 on 2026-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_buyer_order_confirmation_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='client_ack',
            field=models.TextField(blank=True, verbose_name='Текст для клиента (подтверждение)'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий покупателя'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer_name',
            field=models.CharField(max_length=120, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='customer_phone',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='lines',
            field=models.JSONField(default=list, help_text='Список товарных строк из корзины. В каждой позиции: наименование (title), количество (qty), ориентировочная цена (priceFrom), ссылка на карточку в каталоге (slug), идентификаторы товара и варианта на сайте (productId, variantId).', verbose_name='Позиции заказа (данные с сайта)'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='manager_letter',
            field=models.TextField(blank=True, verbose_name='Текст письма менеджеру'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_ref',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='total_approx',
            field=models.PositiveIntegerField(default=0, help_text='Приблизительная сумма в рублях, как передал сайт при оформлении.', verbose_name='Сумма заказа (ориентир)'),
        ),
    ]
