# Generated by Django 6.0.4 on 2026-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_cartorder_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='acquiring_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные эквайринга (ссылка на оплату, id заказа Ozon Pay и т.д.)'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз со склада'), ('cdek', 'СДЭК (ПВЗ / курьер)'), ('ozon_logistics', 'Логистика Ozon')], db_index=True, default='pickup', max_length=32, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cash_pickup', 'Наличные при самовывозе'), ('cod_cdek', 'Наложенный платёж (СДЭК)'), ('card_online', 'Онлайн-оплата (эквайринг Ozon Pay)')], db_index=True, default='cash_pickup', max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_account',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='СДЭК: Account (client_id для OAuth)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_enabled',
            field=models.BooleanField(default=False, help_text='Доставка СДЭК; учётная запись API — ниже. Виджет ПВЗ подключается на фронте (см. docs).', verbose_name='СДЭК: включить на сайте'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_secure_password',
            field=models.CharField(blank=True, default='', help_text='Не публикуйте. Можно задать CDEK_SECURE в .env — приоритет над полем (см. docs).', max_length=256, verbose_name='СДЭК: Secure password (client_secret)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_test_mode',
            field=models.BooleanField(default=True, help_text='Выкл. — боевой https://api.cdek.ru и боевые ключи.', verbose_name='СДЭК: тестовый контур (api.edu.cdek.ru)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_widget_script_url',
            field=models.URLField(blank=True, default='', help_text='Обычно с https://widget.cdek.ru/ — см. документацию виджета и wiki cdek-it/widget.', max_length=512, verbose_name='СДЭК: URL скрипта виджета'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='checkout_pickup_enabled',
            field=models.BooleanField(default=True, help_text='Покупатель может выбрать получение со склада; адрес и режим — поля ниже.', verbose_name='Самовывоз: показывать на сайте'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_logistics_buyer_note',
            field=models.TextField(blank=True, default='', help_text='Кратко опишите условия; ссылка на справку Ozon при необходимости.', verbose_name='Логистика Ozon: текст для покупателя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_logistics_enabled',
            field=models.BooleanField(default=False, help_text='Доступна только онлайн-оплата через Ozon Pay (если эквайринг включён). Подключение кабинета — по инструкции Ozon.', verbose_name='Логистика Ozon: показывать способ доставки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_pay_client_id',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Ozon Pay: Client ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_pay_client_secret',
            field=models.CharField(blank=True, default='', help_text='Храните в секрете. Приоритет: OZON_PAY_CLIENT_SECRET в .env.', max_length=512, verbose_name='Ozon Pay: Client Secret'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_pay_enabled',
            field=models.BooleanField(default=False, help_text='Интеграция по API Ozon Acquiring (Ozon Pay Checkout). Ключи — ниже.', verbose_name='Ozon Pay Checkout: включить онлайн-оплату'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_pay_sandbox',
            field=models.BooleanField(default=True, help_text='Пока нет боевого доступа оставьте включённым.', verbose_name='Ozon Pay: песочница / тест'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_pay_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Заголовок/подпись от Ozon для POST /api/webhooks/ozon-pay/ (настроить после регистрации вебхука).', max_length=256, verbose_name='Ozon Pay: секрет проверки вебхуков'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_address',
            field=models.TextField(blank=True, default='', help_text='Показывается на шаге оформления и в письме клиенту.', verbose_name='Самовывоз: полный адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_hours',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Самовывоз: режим работы выдачи'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Самовывоз: широта (опционально, для карты)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Самовывоз: долгота (опционально)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_note',
            field=models.TextField(blank=True, default='', verbose_name='Самовывоз: как проехать / комментарий'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_point_title',
            field=models.CharField(default='Склад', help_text='Например: «Склад», «Производство».', max_length=200, verbose_name='Самовывоз: название точки'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='delivery_provider',
            field=models.CharField(blank=True, max_length=32, verbose_name='Доставка (код, legacy)'),
        ),
    ]
