# Generated by Django 6.0.4 on 2026-04-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sitesettings_map_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, help_text='SKU в каталоге Ozon для createOrder при доставке Ozon Логистика; если задан у варианта — используется он.', null=True, verbose_name='Ozon SKU (товар)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, help_text='SKU в Ozon для этого предложения (приоритет над SKU товара).', null=True, verbose_name='Ozon SKU (вариант)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cdek_widget_script_url',
            field=models.URLField(blank=True, default='', help_text='Пусто — по умолчанию v3 с jsDelivr: @cdek-it/widget@3. Иначе свой URL (см. wiki cdek-it/widget).', max_length=512, verbose_name='СДЭК: URL скрипта виджета'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_iframe_src',
            field=models.TextField(blank=True, default='', help_text='Только полный src из iframe (не ссылку yandex.ru/maps/…). Яндекс.Карты: в ll и pt — долгота,широта; в URL запятую пишите как %2C, например …?ll=41.124649%2C56.925095&z=16&pt=41.124649%2C56.925095%2Cpm2rdm. Если в адресе вместо запятой оказался символ @ (%41) — метка уедет не туда.', verbose_name='Карта: URL iframe (Яндекс/Google и т.д.)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ozon_pay_client_id',
            field=models.CharField(blank=True, default='', help_text='Из кабинета эквайринга. Env: OZON_PAY_ACCESS_KEY.', max_length=256, verbose_name='Ozon Pay: accessKey (идентификатор токена)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ozon_pay_client_secret',
            field=models.CharField(blank=True, default='', help_text='Для подписи запросов createOrder. Env: OZON_PAY_SECRET_KEY или OZON_PAY_CLIENT_SECRET.', max_length=512, verbose_name='Ozon Pay: secretKey (секрет токена)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ozon_pay_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Секрет для проверки requestSign в POST /api/webhooks/ozon-pay/. Env: OZON_PAY_WEBHOOK_SECRET.', max_length=256, verbose_name='Ozon Pay: notificationSecretKey (уведомления)'),
        ),
    ]
