# Generated by Django 6.0.4 on 2026-04-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sitesettings_cdek_manual_pvz_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проверено менеджером'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда подтверждено'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AddField(
            model_name='review',
            name='publication_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на публикацию'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_from_site',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отправлен с сайта'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='На сайте'),
        ),
    ]
