# Generated by Django 6.0.4 on 2026-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_product_material_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='astrum_crm_contact_behavior',
            field=models.CharField(choices=[('SELECT_EXISTING', 'Искать контакт по телефону/email, иначе создать'), ('CREATE_ANYWAY', 'Всегда создавать новый контакт')], default='SELECT_EXISTING', help_text='Рекомендуется «Искать по телефону/email»: CRM сопоставляет контакт с существующим по телефону и email из заказа; если не найден — создаёт нового. На сайте при оформлении email обязателен.', max_length=32, verbose_name='Поведение с контактами'),
        ),
    ]
