# Generated by Django 6.0.4 on 2026-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_sitesettings_astrum_contact_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_checkout_ui',
            field=models.CharField(choices=[('widget', 'Виджет v3 (карта Яндекса)'), ('custom', 'Свой интерфейс: список ПВЗ по API, без Яндекса')], default='widget', help_text='«Виджет» — официальный виджет cdek-it и ключ Яндекс.Карт. «Свой» — список пунктов из API СДЭК без карты и без ключа Яндекса.', max_length=16, verbose_name='СДЭК: интерфейс выбора ПВЗ на витрине'),
        ),
    ]
