# Generated by Django 6.0.4 on 2026-04-20 04:42

from django.db import migrations, models


def _backfill_goods_subtotal(apps, schema_editor):
    CartOrder = apps.get_model("api", "CartOrder")
    for row in CartOrder.objects.filter(goods_subtotal_approx=0).exclude(total_approx=0).iterator():
        CartOrder.objects.filter(pk=row.pk).update(goods_subtotal_approx=row.total_approx)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sitesettings_cdek_checkout_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='delivery_price_rub',
            field=models.PositiveIntegerField(default=0, help_text='Итоговая доставка к оплате (с учётом бесплатной от суммы в настройках).', verbose_name='Стоимость доставки, ₽'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='goods_subtotal_approx',
            field=models.PositiveIntegerField(default=0, help_text='Сумма по строкам корзины без доставки.', verbose_name='Сумма товаров (ориентир)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_tariff_codes_door',
            field=models.CharField(blank=True, default='', help_text='Тарифы для режима «до двери». Пусто — все.', max_length=500, verbose_name='СДЭК: коды тарифов для курьера до двери'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_tariff_codes_office',
            field=models.CharField(blank=True, default='', help_text='Числовые коды тарифов API СДЭК v2 для доставки в пункт выдачи (виджет). Пусто — доступны все тарифы виджета.', max_length=500, verbose_name='СДЭК: коды тарифов для ПВЗ (через запятую)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_tariff_codes_pickup',
            field=models.CharField(blank=True, default='', help_text='Тарифы для постаматов (если включены в виджете). Пусто — все.', max_length=500, verbose_name='СДЭК: коды тарифов для постаматов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='checkout_free_delivery_from_rub',
            field=models.PositiveIntegerField(default=0, help_text='0 — порог не используется. Если сумма товаров не ниже этого значения, стоимость доставки СДЭК на витрине обнуляется.', verbose_name='Бесплатная доставка от суммы товаров, ₽'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='checkout_minimum_order_rub',
            field=models.PositiveIntegerField(default=0, help_text='0 — без ограничения. Иначе оформление возможно, если сумма товарных позиций не ниже этого порога.', verbose_name='Минимальная сумма заказа (товары), ₽'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='total_approx',
            field=models.PositiveIntegerField(default=0, help_text='Итого к оплате (товары + доставка), как посчитано на сервере при оформлении.', verbose_name='Сумма заказа (ориентир)'),
        ),
        migrations.RunPython(_backfill_goods_subtotal, migrations.RunPython.noop),
    ]
