# Generated by Django 6.0.4 on 2026-04-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_checkout_delivery_and_cdek_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='delivery_price_rub',
            field=models.PositiveIntegerField(default=0, help_text='Доставка к оплате по этому заказу (с учётом порога бесплатной доставки в настройках).', verbose_name='Стоимость доставки, ₽'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='goods_subtotal_approx',
            field=models.PositiveIntegerField(default=0, help_text='Сумма по товарным строкам без доставки.', verbose_name='Сумма товаров (ориентир)'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='total_approx',
            field=models.PositiveIntegerField(default=0, help_text='Итого к оплате: товары и доставка (ориентировочно).', verbose_name='Сумма заказа (ориентир)'),
        ),
    ]
