# Generated by Django 6.0.4 on 2026-04-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_cartorder_help_text_clarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='cdek_tariff_codes_door',
            field=models.CharField(blank=True, default='', help_text='Тарифы для режима «до двери». Пусто — все. Список можно подобрать из API блоком ниже.', max_length=500, verbose_name='СДЭК: коды тарифов для курьера до двери'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cdek_tariff_codes_office',
            field=models.CharField(blank=True, default='', help_text='Числовые коды тарифов API СДЭК v2 для доставки в пункт выдачи (виджет). Пусто — доступны все тарифы виджета. Ниже на странице — загрузка списка из API.', max_length=500, verbose_name='СДЭК: коды тарифов для ПВЗ (через запятую)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cdek_tariff_codes_pickup',
            field=models.CharField(blank=True, default='', help_text='Тарифы для постаматов (если включены в виджете). Пусто — все. Список можно подобрать из API блоком ниже.', max_length=500, verbose_name='СДЭК: коды тарифов для постаматов'),
        ),
    ]
