# Generated by Django 6.0.4 on 2026-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_sitesettings_cdek_tariff_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_portfolio',
            field=models.BooleanField(default=True, help_text='Если выключено, блок портфолио скрыт на главной странице.', verbose_name='Показывать блок портфолио на главной'),
        ),
    ]
