# Generated by Django 6.0.4 on 2026-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_sitesettings_show_portfolio_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_yandex_counter_id',
            field=models.CharField(blank=True, default='', help_text='Только цифры, например 12345678.', max_length=32, verbose_name='Яндекс Метрика: ID счётчика'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_yandex_enabled',
            field=models.BooleanField(default=False, help_text='Включает загрузку тега Метрики на витрине.', verbose_name='Яндекс Метрика: включить счётчик'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_allow_indexing',
            field=models.BooleanField(default=True, help_text='Если выключено, витрина отдает robots noindex,nofollow.', verbose_name='SEO: разрешить индексацию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_meta_description',
            field=models.TextField(blank=True, default='', help_text='Используется, если у конкретной страницы нет своего description.', verbose_name='SEO: мета-описание по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_locale',
            field=models.CharField(blank=True, default='ru_RU', help_text='Open Graph locale, например ru_RU.', max_length=16, verbose_name='SEO: locale'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_region',
            field=models.CharField(blank=True, default='RU', help_text='Код региона для structured data, например RU.', max_length=16, verbose_name='SEO: регион'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_suffix',
            field=models.CharField(blank=True, default='', help_text='Например: «— Фабрика Тентов». Добавляется к заголовкам страниц.', max_length=120, verbose_name='SEO: суффикс title'),
        ),
    ]
