# Generated by Django 6.0.4 on 2026-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_sitesettings_analytics_seo_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='cdek_sync_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток отправки в СДЭК'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='cdek_sync_error',
            field=models.TextField(blank=True, verbose_name='Ошибка синхронизации СДЭК'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='cdek_sync_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает отправки'), ('success', 'Успешно отправлено'), ('error', 'Ошибка отправки')], db_index=True, default='not_required', max_length=24, verbose_name='Синхронизация СДЭК'),
        ),
    ]
