# Generated by Django 6.0.4 on 2026-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_cartorder_cdek_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cdek_height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара.', null=True, verbose_name='СДЭК: высота, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='cdek_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара.', null=True, verbose_name='СДЭК: длина, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='cdek_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Фактический вес одной единицы товара для расчёта доставки и создания накладной.', null=True, verbose_name='СДЭК: вес товара, г'),
        ),
        migrations.AddField(
            model_name='product',
            name='cdek_width_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара.', null=True, verbose_name='СДЭК: ширина, см'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_default_height_cm',
            field=models.PositiveIntegerField(default=20, help_text='Используется, если у товара не заполнена высота.', verbose_name='СДЭК: общая высота по умолчанию, см'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_default_length_cm',
            field=models.PositiveIntegerField(default=30, help_text='Используется, если у товара не заполнена длина.', verbose_name='СДЭК: общая длина по умолчанию, см'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_default_weight_grams',
            field=models.PositiveIntegerField(default=3000, help_text='Используется для расчёта/накладной, если у товара не заполнен вес. Параметры товара имеют приоритет.', verbose_name='СДЭК: общий вес по умолчанию, г'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_default_width_cm',
            field=models.PositiveIntegerField(default=20, help_text='Используется, если у товара не заполнена ширина.', verbose_name='СДЭК: общая ширина по умолчанию, см'),
        ),
    ]
