# Generated by Django 6.0.4 on 2026-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_product_cdek_height_cm_product_cdek_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_recipient_delivery_fee_fixed_rub',
            field=models.PositiveIntegerField(default=0, help_text='Используется, если выбран режим «Фиксированная сумма».', verbose_name='СДЭК: доп. сбор с получателя (фикс), ₽'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_recipient_delivery_fee_mode',
            field=models.CharField(choices=[('off', 'Отключено'), ('fixed', 'Фиксированная сумма (₽)'), ('percent', 'Процент от суммы товаров')], default='off', help_text='Передаётся в delivery_recipient_cost.value (наложенный платёж).', max_length=16, verbose_name='СДЭК: доп. сбор с получателя за доставку'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cdek_recipient_delivery_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется, если выбран режим «Процент от суммы товаров».', max_digits=5, verbose_name='СДЭК: доп. сбор с получателя (% от суммы товаров)'),
        ),
    ]
