# Generated by Django 6.0.4 on 2026-04-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sitesettings_cdek_recipient_delivery_fee_fixed_rub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=500, verbose_name='SEO description')),
                ('body', models.TextField(blank=True, default='', help_text='Поддерживается HTML. Markdown можно хранить как текст и обработать на витрине при необходимости.', verbose_name='Содержимое (HTML или Markdown)')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('show_in_header', models.BooleanField(default=False, verbose_name='Показывать ссылку в шапке')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать ссылку в подвале')),
                ('header_link_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Текст ссылки в шапке')),
                ('footer_link_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Текст ссылки в подвале')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок ссылок')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статичная страница',
                'verbose_name_plural': 'Статичные страницы',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
