# Generated by Django 6.0.4 on 2026-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staticpage_alter_product_cdek_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_body_start_snippet',
            field=models.TextField(blank=True, default='', help_text='HTML/JS, который будет вставлен в начало <body> на витрине.', verbose_name='Аналитика: сниппет после <body>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_head_snippet',
            field=models.TextField(blank=True, default='', help_text='HTML/JS, который будет вставлен в начало <head> на витрине.', verbose_name='Аналитика: сниппет в <head>'),
        ),
    ]
