# Generated by Django 6.0.4 on 2026-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_sitesettings_analytics_body_start_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cdek_height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Если не заполнено — используется общий fallback из настроек интеграции СДЭК.', null=True, verbose_name='СДЭК: высота, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cdek_length_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Если не заполнено — используется общий fallback из настроек интеграции СДЭК.', null=True, verbose_name='СДЭК: длина, см'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cdek_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Фактический вес одной единицы товара для расчёта доставки и создания накладной. Если не заполнено — используется общий fallback из настроек интеграции СДЭК.', null=True, verbose_name='СДЭК: вес товара, г'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cdek_width_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Габарит одной единицы товара. Если не заполнено — используется общий fallback из настроек интеграции СДЭК.', null=True, verbose_name='СДЭК: ширина, см'),
        ),
    ]
