# Generated by Django 6.0.4 on 2026-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_product_cdek_height_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User-Agent')),
                ('consent_value', models.BooleanField(verbose_name='Согласие принято')),
                ('timestamp', models.DateTimeField(verbose_name='Метка времени клиента')),
                ('policy_version', models.CharField(max_length=20, verbose_name='Версия документов')),
                ('url', models.CharField(max_length=500, verbose_name='URL страницы')),
                ('session_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано на сервере')),
            ],
            options={
                'verbose_name': 'Лог согласия на ПДн',
                'verbose_name_plural': 'Логи согласий на ПДн',
                'ordering': ['-created_at'],
            },
        ),
    ]
