# Generated by Django 6.0.4 on 2026-04-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_sitesettings_body_end_cartorder_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_navigation',
            field=models.JSONField(blank=True, default=None, help_text='Порядок и включение пунктов: список объектов с полями key (home|catalog|portfolio|blog|reviews|contacts), enabled, order, label (подпись, необязательно). Пусто — настройки по умолчанию.', null=True, verbose_name='Навигация шапки (JSON)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_yandex_profile_url',
            field=models.URLField(blank=True, default='', help_text='Публичный URL организации (профиль в Яндексе). Ссылка «Все отзывы в Яндексе» на странице /reviews.', max_length=512, verbose_name='Отзывы: ссылка на карточку в Яндексе'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_yandex_widget_html',
            field=models.TextField(blank=True, default='', help_text='Код вставки из кабинета организации (обычно iframe). Показывается на /reviews первым блоком. Автоматическая подгрузка отзывов по URL без виджета невозможна (ограничения Яндекса).', verbose_name='Отзывы: HTML виджета Яндекса'),
        ),
    ]
