# Generated by Django 6.0.4 on 2026-04-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_sitesettings_header_nav_reviews_yandex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — на сайте подставляется «Каталог: возврат по умолчанию» из настроек сайта.', null=True, verbose_name='Возврат, дн (витрина)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто — на сайте подставляется «Каталог: гарантия по умолчанию» из настроек сайта.', null=True, verbose_name='Гарантия, мес (витрина)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_return_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Показ в карточках товара, если у товара не задан свой срок возврата.', verbose_name='Каталог: возврат по умолчанию, дн.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_warranty_months',
            field=models.PositiveSmallIntegerField(default=3, help_text='Показ в карточках товара, если у товара не задана своя гарантия.', verbose_name='Каталог: гарантия по умолчанию, мес.'),
        ),
    ]
