# Generated by Django 6.0.4 on 2026-04-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_catalog_warranty_and_header_nav_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Группа (как в товаре)')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Параметр (как в товаре)')),
                ('label', models.CharField(blank=True, help_text='Пусто — показывать «Параметр»; иначе этот текст (например, короткий заголовок).', max_length=255, verbose_name='Подпись в витрине')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Показывать в фильтре каталога')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Сколько опубликованных товаров содержат эту характеристику — после «Сформировать из товаров».', verbose_name='Товаров с параметром (последний разбор)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Параметр фильтра каталога',
                'verbose_name_plural': 'Фильтр каталога: параметры',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('group_name', 'name'), name='api_catalogfilterkey_group_name_name_uniq')],
            },
        ),
    ]
