# Generated by Django 6.0.4 on 2026-04-27 05:02

from django.db import migrations, models


def seed_o_nas_about_payload(apps, schema_editor):
    from api.about_page_defaults import default_about_page_payload

    StaticPage = apps.get_model("api", "StaticPage")
    row = StaticPage.objects.filter(slug="o-nas").first()
    if not row:
        return
    if row.about_payload:
        return
    row.about_payload = default_about_page_payload()
    row.save(update_fields=["about_payload"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_static_page_o_nas'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='about_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Если задан валидный JSON с version: 1, на витрине показывается расширенный макет; иначе — только поле «Содержимое».', verbose_name='Макет «О нас» (JSON)'),
        ),
        migrations.RunPython(seed_o_nas_about_payload, reverse_noop),
    ]
