# Generated by Django 6.0.4 on 2026-04-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_staticpage_about_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='about_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Заполняется полями раздела «Макет «О нас» — витрина» в админке для страницы со слагом o-nas. Если пусто — на сайте используется только «Содержимое».', verbose_name='Макет «О нас» (витрина, JSON)'),
        ),
    ]
