# Generated by Django 6.0.4 on 2026-04-27 05:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_staticpage_about_manufacturer_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_description_max',
            field=models.PositiveSmallIntegerField(default=160, help_text='Подсказка для витрины: обрезка автоматически сгенерированных описаний (текст из каталога, блог и т.д.).', verbose_name='SEO: max длина meta description (символы)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_og_image',
            field=models.ImageField(blank=True, help_text='Используется в Open Graph, если у страницы нет своего изображения (тематическое 1200×630 или квадрат, до ~2 МБ).', max_length=512, null=True, upload_to='branding/seo-og/%Y/%m/', verbose_name='SEO: изображение по умолчанию (og:image)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_separator',
            field=models.CharField(blank=True, default=' | ', help_text='Например « | » или « — ». Подставляется в шаблоны, где указано {sep}.', max_length=16, verbose_name='SEO: разделитель в шаблоне title (плейсхолдер {sep})'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_templates',
            field=models.JSONField(blank=True, default=api.models.default_seo_title_templates, help_text='JSON. Ключи: home, listing, static, article, emdash. Плейсхолдеры: {title}, {siteName}, {suffix} (суффикс из поля «суффикс title»), {sep}. Пустой home — как сейчас: заголовок из контента главной + суффикс. Перекрытие: у статичных страниц, товаров и блога заполненный в карточке meta title важнее шаблона.', verbose_name='SEO: шаблоны <title> по типам страниц'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', help_text='summary или summary_large_image (как у крупных CMS: карточка в соцсетях).', max_length=32, verbose_name='SEO: Twitter / X card'),
        ),
    ]
