# Generated by Django 6.0.4 on 2026-04-27 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_sitesettings_seo_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='about_intro_image',
            field=models.ImageField(blank=True, help_text='Колонка справа от «Узнай нас / …». Если задано — подменяет URL картинки из макета.', max_length=512, null=True, upload_to='static_pages/about_intro/%Y/%m/', verbose_name='Вступление: фото (файл, справа от заголовка)'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='about_intro_video',
            field=models.FileField(blank=True, help_text='MP4/WebM; встроенное видео справа. Если задано — подменяет внешнюю ссылку на видео из макета.', max_length=512, null=True, upload_to='static_pages/about_intro/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'ogg'])], verbose_name='Вступление: видео (файл, справа)'),
        ),
    ]
