# Generated by Django 6.0.4 on 2026-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_staticpage_about_intro_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ozon_logistics_delivery_payer',
            field=models.CharField(choices=[('store', 'Доставка за счёт магазина'), ('buyer', 'Доставка за счёт покупателя')], default='store', help_text='Показ текста на оформлении заказа. Итог с доставкой считает Ozon Pay при оплате.', max_length=16, verbose_name='Логистика Ozon: кто оплачивает доставку (на витрине)'),
        ),
    ]
