# Generated by Django 6.0.4 on 2026-04-28 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_sitesettings_ozon_logistics_delivery_payer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSpotlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=512, upload_to='static_pages/about_spotlight/%Y/%m/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, default='', max_length=500, verbose_name='Подпись (alt)')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('static_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_spotlight_items', to='api.staticpage', verbose_name='страница')),
            ],
            options={
                'verbose_name': 'фото из галереи (О нас — витрина)',
                'verbose_name_plural': 'Галерея (О нас, витрина): фото, перетаскивание в рамку, порядок',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
