# Generated by Django 6.0.4 on 2026-05-01 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_sitesettings_checkout_orders_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг (URL)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('body', models.TextField(blank=True, help_text='Простой текст или разметка; на витрине выводится с переносами строк.', verbose_name='Текст на странице акции')),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='promotions/%Y/%m/', verbose_name='Изображение')),
                ('starts_at', models.DateTimeField(verbose_name='Дата начала')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Пусто — акция без конечной даты.', null=True, verbose_name='Дата окончания')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списках')),
                ('applies_to_all_products', models.BooleanField(default=False, help_text='Если включено, скидка действует на все опубликованные товары в каталоге.', verbose_name='На весь каталог')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='0 — информационная акция (цены в каталоге не меняются). 1–100 — скидка от цены в каталоге.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Имеет смысл, если «На весь каталог» выключено: акция только на выбранные позиции.', related_name='promotions', to='api.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['sort_order', '-starts_at', 'id'],
            },
        ),
    ]
