# Generated by Django 6.0.4 on 2026-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_sitesettings_market_goods_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, help_text='Числовой SKU товара в Ozon (как в карточке продавца) — в Acquiring createOrder уходит в items[].sku при доставке «Логистика Ozon»; без него payapi не сопоставит позицию с доставкой. Если задан у варианта — используется SKU варианта.', null=True, verbose_name='Ozon SKU (товар)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, help_text='Числовой SKU этого предложения в Ozon для createOrder (приоритет над SKU товара); тот же идентификатор, что для проверки остатков Seller API перед оплатой.', null=True, verbose_name='Ozon SKU (вариант)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='stack_with_others',
            field=models.BooleanField(default=False, help_text='Включите, если эту скидку нужно складывать с другими суммируемыми акциями на тот же товар. Выключено — участвует в правиле «максимум среди несуммируемых», затем к результату добавляются суммируемые.', verbose_name='Суммировать с другими акциями'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ozon_pay_enabled',
            field=models.BooleanField(default=False, help_text='Интеграция по API Ozon Acquiring (Ozon Pay Checkout). Ключи — ниже. Цены позиций в кабинете эквайринга при изменении на Ozon при необходимости обновляйте там вручную (автоперенос цен с Seller — по правилам Ozon, не через сайт).', verbose_name='Ozon Pay Checkout: включить онлайн-оплату'),
        ),
    ]
