# Generated by Django 6.0.4 on 2026-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_product_ozon_sku_alter_productvariant_ozon_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_1_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 1: видео (файл)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_2_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 2: видео (файл)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_3_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 3: видео (файл)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_4_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 4: видео (файл)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_5_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 5: видео (файл)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_6_video',
            field=models.FileField(blank=True, help_text='Опционально. Запускается поверх картинки, если ролик доступен в браузере.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 6: видео (файл)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_1_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 1: изображение (постер и запасной фон, если видео не играет)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_2_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 2: изображение (постер и запасной фон, если видео не играет)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_3_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 3: изображение (постер и запасной фон, если видео не играет)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_4_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 4: изображение (постер и запасной фон, если видео не играет)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_5_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 5: изображение (постер и запасной фон, если видео не играет)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_slide_6_image',
            field=models.FileField(blank=True, help_text='Картинка показывается сразу и остаётся под видео; при ошибке ролика остаётся только она. Раньше сюда же можно было загрузить видео — такие файлы по-прежнему обрабатываются.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 6: изображение (постер и запасной фон, если видео не играет)'),
        ),
    ]
