# Generated by Django 6.0.4 on 2026-05-06 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_homepagecontent_hero_slide_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Интерактивный просмотр на странице товара (модалка). Форматы FBX/OBJ на сайт не подходят — экспортируйте в .glb.', max_length=512, null=True, upload_to='products/3d/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb'], message='Загрузите файл в формате .glb (glTF Binary).')], verbose_name='3D-модель (glTF бинарный, .glb)'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_3d_poster',
            field=models.ImageField(blank=True, help_text='Картинка до загрузки модели и на карточке товара в сетке каталога (если задана 3D-модель).', max_length=512, null=True, upload_to='products/3d/posters/%Y/%m/', verbose_name='Постер для 3D (JPEG/WebP)'),
        ),
    ]
