# Generated by Django 6.0.4 on 2026-05-07 04:35
#
# MySQL: колонки могли появиться вне этой миграции (ручной ALTER / сбой учёта).
# Тогда повторное AddField даёт 1060 Duplicate column — обходим через
# add_field только для отсутствующих колонок.

from django.db import migrations, models


def _upload_slides():
    return "home/hero/slides/%Y/%m/"


def _add_homepage_hero_mobile_fields_if_missing(apps, schema_editor):
    HomePageContent = apps.get_model("api", "HomePageContent")
    table = HomePageContent._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
    existing = {getattr(col, "name", col[0]) for col in desc}

    specs: list[tuple[str, models.FileField]] = [
        (
            "hero_slide_1_mobile_image",
            models.FileField(
                blank=True,
                help_text=(
                    "Отдельный постер для узких экранов. Рекомендуемый кадр 430×430 px (до 430×448). "
                    "Пусто — на телефоне используется картинка для ПК."
                ),
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 1: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_1_mobile_video",
            models.FileField(
                blank=True,
                help_text="Отдельный ролик для узких экранов. Пусто — на телефоне то же видео, что и для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 1: видео для мобильных",
            ),
        ),
        (
            "hero_slide_2_mobile_image",
            models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 2: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_2_mobile_video",
            models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 2: видео для мобильных",
            ),
        ),
        (
            "hero_slide_3_mobile_image",
            models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 3: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_3_mobile_video",
            models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 3: видео для мобильных",
            ),
        ),
        (
            "hero_slide_4_mobile_image",
            models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 4: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_4_mobile_video",
            models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 4: видео для мобильных",
            ),
        ),
        (
            "hero_slide_5_mobile_image",
            models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 5: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_5_mobile_video",
            models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 5: видео для мобильных",
            ),
        ),
        (
            "hero_slide_6_mobile_image",
            models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 6: изображение для мобильных",
            ),
        ),
        (
            "hero_slide_6_mobile_video",
            models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to=_upload_slides(),
                verbose_name="Hero, слайд 6: видео для мобильных",
            ),
        ),
    ]

    for name, field in specs:
        if name in existing:
            continue
        field.set_attributes_from_name(name)
        schema_editor.add_field(HomePageContent, field)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0082_product_model_3d_glb"),
    ]

    state_operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_1_mobile_image",
            field=models.FileField(
                blank=True,
                help_text=(
                    "Отдельный постер для узких экранов. Рекомендуемый кадр 430×430 px (до 430×448). "
                    "Пусто — на телефоне используется картинка для ПК."
                ),
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 1: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_1_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Отдельный ролик для узких экранов. Пусто — на телефоне то же видео, что и для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 1: видео для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_2_mobile_image",
            field=models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 2: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_2_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 2: видео для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_3_mobile_image",
            field=models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 3: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_3_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 3: видео для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_4_mobile_image",
            field=models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 4: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_4_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 4: видео для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_5_mobile_image",
            field=models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 5: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_5_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 5: видео для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_6_mobile_image",
            field=models.FileField(
                blank=True,
                help_text="Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 6: изображение для мобильных",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_slide_6_mobile_video",
            field=models.FileField(
                blank=True,
                help_text="Пусто — видео для ПК.",
                max_length=512,
                null=True,
                upload_to="home/hero/slides/%Y/%m/",
                verbose_name="Hero, слайд 6: видео для мобильных",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[
                migrations.RunPython(_add_homepage_hero_mobile_fields_if_missing, migrations.RunPython.noop),
            ],
        ),
    ]
