# Generated by Django 6.0.4 on 2026-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_product_model_3d_glb'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_1_mobile_image',
            field=models.FileField(blank=True, help_text='Отдельный постер для узких экранов. Рекомендуемый кадр 430×430 px (до 430×448). Пусто — на телефоне используется картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 1: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_1_mobile_video',
            field=models.FileField(blank=True, help_text='Отдельный ролик для узких экранов. Пусто — на телефоне то же видео, что и для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 1: видео для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_2_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 2: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_2_mobile_video',
            field=models.FileField(blank=True, help_text='Пусто — видео для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 2: видео для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_3_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 3: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_3_mobile_video',
            field=models.FileField(blank=True, help_text='Пусто — видео для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 3: видео для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_4_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 4: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_4_mobile_video',
            field=models.FileField(blank=True, help_text='Пусто — видео для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 4: видео для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_5_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 5: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_5_mobile_video',
            field=models.FileField(blank=True, help_text='Пусто — видео для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 5: видео для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_6_mobile_image',
            field=models.FileField(blank=True, help_text='Рекомендуемый кадр 430×430 px (до 430×448). Пусто — картинка для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 6: изображение для мобильных'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_slide_6_mobile_video',
            field=models.FileField(blank=True, help_text='Пусто — видео для ПК.', max_length=512, null=True, upload_to='home/hero/slides/%Y/%m/', verbose_name='Hero, слайд 6: видео для мобильных'),
        ),
    ]
