# Generated by Django 6.0.4 on 2026-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_homepagecontent_hero_slide_mobile_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_3d_poster',
            field=models.ImageField(blank=True, help_text='Не используется на витрине: фото — только «Фотографии товара». Поле оставлено в БД для старых записей.', max_length=512, null=True, upload_to='products/3d/posters/%Y/%m/', verbose_name='Постер для 3D (устар., не на сайте)'),
        ),
    ]
