# Generated by Django 6.0.4 on 2026-05-07 06:59

import django.db.models.deletion
from django.db import migrations, models


def _migrate_product_slugs_and_seo_defaults(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    Redirect = apps.get_model("api", "CatalogProductSlugRedirect")
    SiteSettings = apps.get_model("api", "SiteSettings")

    try:
        from slugify import slugify as py_slugify
    except ImportError:  # pragma: no cover
        return

    def latin_slug(text: str, max_length: int) -> str:
        base = py_slugify((text or "").strip() or "item", max_length=max_length, word_boundary=True, lowercase=True)
        base = (base or "item").strip("-")[:max_length] or "item"
        return base[:max_length]

    def pc_slug(title: str, pk: int, max_length: int = 120) -> str:
        id_part = str(int(pk))
        max_base = max_length - 1 - len(id_part)
        if max_base < 3:
            max_base = 3
        base = latin_slug((title or "").strip() or "item", max_base)
        return f"{base}-{id_part}"[:max_length]

    for p in Product.objects.all().order_by("id"):
        old = (p.slug or "").strip()
        new = pc_slug(p.title, p.pk)
        if old != new:
            if not Redirect.objects.filter(old_slug=old).exists():
                Redirect.objects.create(old_slug=old, product_id=p.pk)
            Product.objects.filter(pk=p.pk).update(slug=new)

    ss = SiteSettings.objects.filter(pk=1).first()
    if ss:
        updates: list[str] = []
        if not (getattr(ss, "seo_catalog_listing_meta_description", None) or "").strip():
            ss.seo_catalog_listing_meta_description = (
                "Каталог тентов, навесов и чехлов от производителя в Иваново. "
                "Готовые размеры и индивидуальный пошив. Цены от 810 ₽. Доставка по всей России."
            )
            updates.append("seo_catalog_listing_meta_description")
        if not (ss.seo_default_meta_description or "").strip():
            ss.seo_default_meta_description = (
                "Производство и продажа тентов, навесов и чехлов в Иваново. "
                "Индивидуальный пошив, доставка по РФ. Гарантия 3 месяца. Звоните: +7 901 696-32-26"
            )
            updates.append("seo_default_meta_description")
        raw_tpl = getattr(ss, "seo_title_templates", None)
        tpl = dict(raw_tpl) if isinstance(raw_tpl, dict) else {}
        if not (tpl.get("home") or "").strip():
            tpl["home"] = "Производство тентов и навесов в Иваново | {siteName}"
            ss.seo_title_templates = tpl
            updates.append("seo_title_templates")
        if updates:
            ss.save(update_fields=updates)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_alter_product_model_3d_poster_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogProductSlugRedirect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_slug", models.SlugField(max_length=120, unique=True, verbose_name="Прежний слаг в URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_slug_redirects",
                        to="api.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Редирект URL товара (старый слаг)",
                "verbose_name_plural": "Редиректы URL товаров",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_catalog_listing_meta_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Сниппет именно для страницы каталога. Пусто — на витрине используется «мета-описание по умолчанию».",
                verbose_name="SEO: meta description листинга каталога (/catalog)",
            ),
        ),
        migrations.RunPython(_migrate_product_slugs_and_seo_defaults, _noop),
    ]
