"""
Блоки формы «Главная страница (контент)»: якоря и пункты сайдбара.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from config.hero_block_fields import all_hero_section_field_names

# slug → заголовок fieldset в админке, короткий заголовок в меню, иконка Material Symbols.
SECTIONS: dict[str, dict[str, Any]] = {
    "meta": {
        "title": _("SEO и микроразметка (главная)"),
        "nav": _("SEO и микроразметка"),
        "icon": "travel_explore",
    },
    "hero": {
        "title": _("Hero: слайд 1 (первый экран)"),
        "nav": _("Hero"),
        "icon": "view_carousel",
    },
    "ps": {
        "title": _("Блок «Проблема — решение» (4 карточки)"),
        "nav": _("Проблема — решение"),
        "icon": "quiz",
    },
    "proc": {
        "title": _("Блок «От замера до монтажа»"),
        "nav": _("От замера до монтажа"),
        "icon": "timeline",
    },
    "paths": {
        "title": _("Блок «Как оформить заказ» (2 сценария)"),
        "nav": _("Как оформить заказ"),
        "icon": "call_split",
    },
    "tent": {
        "title": _("Блок «Виды тентов»"),
        "nav": _("Виды тентов"),
        "icon": "category",
    },
    "feat": {
        "title": _("Блок «Подборка на главной»"),
        "nav": _("Подборка на главной"),
        "icon": "star",
    },
    "calc": {
        "title": _("Блок «Калькулятор»"),
        "nav": _("Калькулятор"),
        "icon": "calculate",
    },
    "port": {
        "title": _("Блок «Портфолио»"),
        "nav": _("Портфолио"),
        "icon": "photo_camera",
    },
    "why": {
        "title": _("Блок «Почему мы» (счётчики и 4 колонки)"),
        "nav": _("Почему мы"),
        "icon": "bolt",
    },
    "rev": {
        "title": _("Блок «Отзывы»"),
        "nav": _("Отзывы"),
        "icon": "reviews",
    },
    "blog": {
        "title": _("Блок «Блог» (превью на главной)"),
        "nav": _("Блог (превью)"),
        "icon": "article",
    },
    "map": {
        "title": _("Блок «Карта и форма» (главная и /contacts)"),
        "nav": _("Карта и форма"),
        "icon": "map",
    },
    "ui": {
        "title": _("Интерфейс витрины (шапка, корзина, оформление)"),
        "nav": _("Интерфейс витрины"),
        "icon": "tune",
    },
}

SECTION_ORDER: tuple[str, ...] = tuple(SECTIONS.keys())

# Виртуальные поля формы главной (и файлы hero_slide_*) по блокам.
SECTION_FIELDS: dict[str, tuple[str, ...]] = {
    "meta": ("meta_title", "meta_description", "meta_org_name", "meta_org_description"),
    "hero": all_hero_section_field_names(),
    "ps": (
        "ps_heading",
        "ps_subheading",
        "ps0_problem",
        "ps0_solution",
        "ps0_icon_kind",
        "ps0_icon",
        "ps0_fa_preset",
        "ps0_fontawesome",
        "ps0_icon_image",
        "ps1_problem",
        "ps1_solution",
        "ps1_icon_kind",
        "ps1_icon",
        "ps1_fa_preset",
        "ps1_fontawesome",
        "ps1_icon_image",
        "ps2_problem",
        "ps2_solution",
        "ps2_icon_kind",
        "ps2_icon",
        "ps2_fa_preset",
        "ps2_fontawesome",
        "ps2_icon_image",
        "ps3_problem",
        "ps3_solution",
        "ps3_icon_kind",
        "ps3_icon",
        "ps3_fa_preset",
        "ps3_fontawesome",
        "ps3_icon_image",
    ),
    "proc": (
        "proc_heading",
        "proc_subheading",
        "proc_s0_title",
        "proc_s0_text",
        "proc_s1_title",
        "proc_s1_text",
        "proc_s2_title",
        "proc_s2_text",
        "proc_s3_title",
        "proc_s3_text",
    ),
    "paths": (
        "paths_eyebrow",
        "paths_heading",
        "paths_subheading",
        "paths_ready_title",
        "paths_ready_subtitle",
        "paths_ready_b0",
        "paths_ready_b1",
        "paths_ready_b2",
        "paths_ready_cta",
        "paths_ready_href",
        "paths_custom_title",
        "paths_custom_subtitle",
        "paths_custom_b0",
        "paths_custom_b1",
        "paths_custom_b2",
        "paths_custom_cta",
        "paths_custom_href",
    ),
    "tent": ("tt_heading", "tt_subheading"),
    "feat": ("feat_heading", "feat_subheading", "feat_catalog_cta"),
    "calc": (
        "calc_mode",
        "calc_heading",
        "calc_subheading",
        "calc_length_label",
        "calc_width_label",
        "calc_material_label",
        "calc_options_label",
        "calc_estimate_label",
        "calc_estimate_note",
        "calc_name_label",
        "calc_phone_label",
        "calc_comment_label",
        "calc_name_placeholder",
        "calc_phone_placeholder",
        "calc_comment_placeholder",
        "calc_submit_button",
        "calc_submitting",
        "calc_success_message",
        "calc_request_title",
        "calc_request_subtitle",
        "calc_request_benefit_1",
        "calc_request_benefit_2",
        "calc_request_benefit_3",
        "calc_step_1_title",
        "calc_step_2_title",
        "calc_virtual_ruler_title",
        "calc_request_badge",
        "calc_error_phone_incomplete",
        "calc_error_comment_too_long",
        "calc_error_submit_failed",
        "calc_error_network",
        "calc_consent_prefix",
        "calc_consent_privacy_link",
        "calc_consent_and",
        "calc_consent_offer_link",
        "calc_pricing_model",
        "calc_range_len_min",
        "calc_range_len_max",
        "calc_range_wid_min",
        "calc_range_wid_max",
        "calc_min_total_rub",
        "calc_round_step",
        "calc_m0_id",
        "calc_m0_label",
        "calc_m0_price_m2",
        "calc_m1_id",
        "calc_m1_label",
        "calc_m1_price_m2",
        "calc_m2_id",
        "calc_m2_label",
        "calc_m2_price_m2",
        "calc_m3_id",
        "calc_m3_label",
        "calc_m3_price_m2",
        "calc_m4_id",
        "calc_m4_label",
        "calc_m4_price_m2",
        "calc_o0_id",
        "calc_o0_label",
        "calc_o0_price",
        "calc_o1_id",
        "calc_o1_label",
        "calc_o1_price",
        "calc_o2_id",
        "calc_o2_label",
        "calc_o2_price",
        "calc_o3_id",
        "calc_o3_label",
        "calc_o3_price",
        "calc_o4_id",
        "calc_o4_label",
        "calc_o4_price",
        "calc_o5_id",
        "calc_o5_label",
        "calc_o5_price",
    ),
    "port": (
        "port_heading",
        "port_subheading",
        "port_page_heading",
        "port_page_subheading",
        "port_filters",
        "port_loading",
        "port_empty",
        "port_all_cta",
    ),
    "why": (
        "why_heading",
        "why_subheading",
        "why_s0_value",
        "why_s0_suffix",
        "why_s0_label",
        "why_s1_value",
        "why_s1_suffix",
        "why_s1_label",
        "why_s2_value",
        "why_s2_suffix",
        "why_s2_label",
        "why_c0_title",
        "why_c0_text",
        "why_c0_icon_kind",
        "why_c0_icon",
        "why_c0_fa_preset",
        "why_c0_fontawesome",
        "why_c1_title",
        "why_c1_text",
        "why_c1_icon_kind",
        "why_c1_icon",
        "why_c1_fa_preset",
        "why_c1_fontawesome",
        "why_c2_title",
        "why_c2_text",
        "why_c2_icon_kind",
        "why_c2_icon",
        "why_c2_fa_preset",
        "why_c2_fontawesome",
        "why_c3_title",
        "why_c3_text",
        "why_c3_icon_kind",
        "why_c3_icon",
        "why_c3_fa_preset",
        "why_c3_fontawesome",
    ),
    "rev": (
        "rev_heading",
        "rev_subheading",
        "rev_loading",
        "rev_video_caption",
        "rev_read_more_label",
        "rev_collapse_label",
        "rev_form_heading",
        "rev_form_subheading",
        "rev_name_placeholder",
        "rev_city_placeholder",
        "rev_text_placeholder",
        "rev_consent_prefix",
        "rev_consent_link_label",
        "rev_submit_button",
        "rev_submitting",
        "rev_success_message",
        "rev_error_message",
    ),
    "blog": (
        "blog_heading",
        "blog_subheading",
        "blog_all_link",
        "blog_read_more",
        "blog_loading",
    ),
    "map": (
        "map_heading",
        "map_subheading",
        "map_iframe_src",
        "map_title",
        "map_form_name_label",
        "map_form_phone_label",
        "map_form_comment_label",
        "map_name_placeholder",
        "map_phone_placeholder",
        "map_comment_placeholder",
        "map_submit_button",
    ),
    "ui": (
        "ui_loading_featured",
        "ui_buy_marketplaces",
        "ui_buy_marketplaces_mobile",
        "ui_nav_home",
        "ui_nav_catalog",
        "ui_nav_about",
        "ui_about_page_slug",
        "ui_nav_reviews",
        "ui_nav_portfolio",
        "ui_nav_contacts",
        "ui_nav_blog",
        "ui_nav_cart",
        "ui_nav_account",
        "ui_nav_menu_title",
        "ui_nav_menu_subtitle",
        "ui_mobile_bar_profile",
        "ui_footer_nav_title",
        "ui_footer_marketplaces_title",
        "ui_footer_social_title",
        "ui_footer_contacts_title",
        "ui_footer_payment_title",
        "ui_footer_delivery_title",
        "ui_footer_staff_login",
        "ui_footer_privacy_link",
        "ui_footer_offer_link",
        "ui_footer_copyright_suffix",
        "ui_header_main_menu_aria",
        "ui_header_theme_to_light_aria",
        "ui_header_theme_to_dark_aria",
        "ui_header_theme_light_title",
        "ui_header_theme_dark_title",
        "ui_header_menu_open_aria",
        "ui_header_menu_close_aria",
        "ui_header_mobile_menu_aria",
        "ui_header_bottom_nav_aria",
        "ui_staff_modal_close_overlay_aria",
        "ui_staff_modal_close_button_aria",
        "ui_staff_modal_title",
        "ui_staff_modal_subtitle",
        "ui_staff_modal_manager_label",
        "ui_staff_modal_manager_hint",
        "ui_staff_modal_admin_label",
        "ui_staff_modal_admin_hint",
        "ui_intro_aria_label",
        "ui_intro_tag_1",
        "ui_intro_tag_2",
        "ui_intro_tag_3",
        "ui_intro_title",
        "ui_intro_subtitle",
        "ui_intro_stage_1",
        "ui_intro_stage_2",
        "ui_intro_stage_3",
        "ui_intro_skip_button",
        "ui_product_no_photo",
        "ui_product_price_prefix",
        "ui_product_add_to_cart",
        "ui_product_added_title",
        "ui_product_continue_shopping",
        "ui_product_go_to_cart",
        "ui_product_marketplaces_title",
        "ui_product_badge_in_stock",
        "ui_product_badge_seasonal",
        "ui_cart_page_title",
        "ui_cart_page_intro",
        "ui_cart_empty_title",
        "ui_cart_empty_text",
        "ui_cart_empty_cta",
        "ui_cart_items_title",
        "ui_cart_no_photo",
        "ui_cart_price_per_unit_prefix",
        "ui_cart_price_per_unit_suffix",
        "ui_cart_qty_label",
        "ui_cart_remove_or_decrease_aria",
        "ui_cart_increase_aria",
        "ui_cart_remove_line",
        "ui_cart_add_more_cta",
        "ui_cart_summary_title",
        "ui_cart_summary_items_label",
        "ui_cart_summary_approx_label",
        "ui_cart_summary_delivery_note",
        "ui_cart_checkout_button",
        "ui_cart_checkout_footnote",
        "ui_cart_terms_prefix",
        "ui_checkout_settings_loading",
        "ui_checkout_delivery_intro",
        "ui_checkout_no_delivery_banner",
        "ui_checkout_no_delivery_inline_error",
        "ui_checkout_ozon_partial_warning",
        "ui_checkout_cdek_after_submit_warning",
        "ui_checkout_online_pay_link_error",
        "ui_checkout_cdek_map_missing_key_help",
        "ui_checkout_cdek_map_missing_service_help",
        "ui_checkout_cdek_map_init_failed_help",
        "ui_checkout_cdek_address_suggest_footer",
        "ui_one_click_consent_tail",
        "ui_product_not_found_title",
        "ui_product_not_found_text",
        "ui_product_back_to_catalog",
        "ui_product_breadcrumb_aria",
        "ui_product_breadcrumb_home",
        "ui_product_breadcrumb_catalog",
        "ui_product_price_label",
        "ui_product_variant_label",
        "ui_product_details_button",
        "ui_product_marketplaces_card_title",
        "ui_product_marketplaces_card_hint",
        "ui_product_custom_order_cta",
        "ui_product_related_title",
        "ui_product_related_subtitle_prefix",
        "ui_product_material_map_subtitle_fallback",
    ),
}


def homepage_full_form_field_order() -> tuple[str, ...]:
    """Порядок отображения полей формы «Главная (контент)» (editor / section).

    Иначе ModelForm ставит model FileField (hero_slide_*_image и т.д.) в начало,
    и чекбоксы «показать бейдж / доверие / KPI» оказываются ниже вместо логичного
    сценария настроек (см. `SECTION_ORDER` + `SECTION_FIELDS` по слайдам).
    """
    names: list[str] = []
    for slug in SECTION_ORDER:
        names.extend(SECTION_FIELDS[slug])
    return tuple(names)


def hp_fieldset(slug: str, fieldset_options: dict[str, Any]) -> tuple[Any, dict[str, Any]]:
    """Fieldset для HomePageContentAdmin: класс fs-id-<slug> (для совместимости)."""
    if slug not in SECTIONS:
        raise KeyError(f"Unknown homepage section slug: {slug}")
    opts = {**fieldset_options}
    classes: Sequence[str] | str = opts.get("classes") or ()
    if isinstance(classes, str):
        classes = (classes,)
    opts["classes"] = tuple(classes) + (f"fs-id-{slug}",)
    return (SECTIONS[slug]["title"], opts)


def homepage_sidebar_block_items() -> list[dict[str, Any]]:
    """Подпункты меню «Главная страница» → отдельная страница блока.

    reverse_lazy — см. site_settings_sidebar_block_items (Unfold + active).
    """
    items: list[dict[str, Any]] = [
        {
            "title": _("Порядок и включение"),
            "icon": "reorder",
            "link": reverse_lazy("admin:api_homepagecontent_section_layout"),
        }
    ]
    for slug in SECTION_ORDER:
        meta = SECTIONS[slug]
        items.append(
            {
                "title": meta["nav"],
                "icon": meta["icon"],
                "link": reverse_lazy(
                    "admin:api_homepagecontent_section", kwargs={"slug": slug}
                ),
            }
        )
    return items
