# Generated by Django 5.2.12 on 2026-04-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=2048)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material_id', models.CharField(max_length=64)),
                ('material_label', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('estimated_price_rub', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка (калькулятор)',
                'verbose_name_plural': 'Заявки калькулятора',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(db_index=True, max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=40)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_comment', models.TextField(blank=True)),
                ('lines', models.JSONField(default=list)),
                ('total_approx', models.PositiveIntegerField(default=0)),
                ('manager_letter', models.TextField(blank=True)),
                ('client_ack', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ (корзина)',
                'verbose_name_plural': 'Заказы корзины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('before_image', models.URLField(blank=True, max_length=2048)),
                ('after_image', models.URLField(blank=True, max_length=2048)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('excerpt', models.TextField(blank=True, verbose_name='Кратко')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('truck', 'Для транспорта'), ('warehouse', 'Ангары и склады'), ('cafe', 'Кафе и террасы'), ('events', 'Мероприятия')], db_index=True, max_length=32, verbose_name='Категория')),
                ('price_from', models.PositiveIntegerField(default=0, verbose_name='Цена от, ₽')),
                ('show_on_home', models.BooleanField(db_index=True, default=False, verbose_name='Показывать на главной')),
                ('teasers', models.JSONField(blank=True, default=list, verbose_name='Тизеры')),
                ('marketplace_links', models.JSONField(blank=True, default=dict, verbose_name='Ссылки МП')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликован')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('photo_url', models.URLField(blank=True, max_length=2048)),
                ('video_url', models.URLField(blank=True, max_length=2048)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='URL изображения')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_rel', to='api.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
