# Generated by Django 5.2.13 on 2026-04-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model("api", "SiteSettings")
    SiteSettings.objects.get_or_create(
        pk=1,
        defaults={
            "show_marketplace_wb": True,
            "show_marketplace_ozon": True,
            "show_marketplace_ym": False,
            "show_marketplace_avito": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartorder_integration_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('show_marketplace_wb', models.BooleanField(default=True, verbose_name='Показывать Wildberries')),
                ('show_marketplace_ozon', models.BooleanField(default=True, verbose_name='Показывать Ozon')),
                ('show_marketplace_ym', models.BooleanField(default=False, verbose_name='Показывать Яндекс Маркет')),
                ('show_marketplace_avito', models.BooleanField(default=False, verbose_name='Показывать Авито')),
                ('global_url_wb', models.URLField(blank=True, max_length=512, verbose_name='URL витрины WB (общий)')),
                ('global_url_ozon', models.URLField(blank=True, max_length=512, verbose_name='URL витрины Ozon (общий)')),
                ('global_url_ym', models.URLField(blank=True, max_length=512, verbose_name='URL Яндекс Маркет (общий)')),
                ('global_url_avito', models.URLField(blank=True, max_length=512, verbose_name='URL Авито (общий)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RunPython(seed_site_settings, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль покупателя',
                'verbose_name_plural': 'Профили покупателей',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Адрес', max_length=64, verbose_name='Название')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=32, verbose_name='Дом / корпус')),
                ('apartment', models.CharField(blank=True, max_length=32, verbose_name='Квартира / офис')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Индекс')),
                ('recipient_name', models.CharField(blank=True, max_length=120, verbose_name='Получатель')),
                ('recipient_phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон получателя')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
