# Generated by Django 5.2.12 on 2026-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_portfolio_review_blog_images_and_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='На сайте'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='estimated_price_rub',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка, ₽'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='length_m',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Длина, м'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='material_id',
            field=models.CharField(max_length=64, verbose_name='ID материала (код)'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='material_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Материал (подпись)'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='options',
            field=models.JSONField(blank=True, default=list, verbose_name='Опции (JSON)'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='calculatorlead',
            name='width_m',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ширина, м'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(blank=True, max_length=64, verbose_name='Категория / подпись'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='completed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='На сайте'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='На сайте'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Видео (URL)'),
        ),
    ]
