# Generated by Django 5.2.12 on 2026-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sync_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_from',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, ₽'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_from',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, ₽'),
        ),
    ]
