# Generated by Django 6.0.4 on 2026-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitesettings_show_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Только загрузка файла. Без изображения на сайте используется запасной фон витрины.', max_length=512, null=True, upload_to='home/hero/%Y/%m/', verbose_name='Фон героя (первый экран)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='blog/covers/%Y/%m/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='after_image_file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='portfolio/%Y/%m/', verbose_name='Фото «после»'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='before_image_file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='portfolio/%Y/%m/', verbose_name='Фото «до»'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo_file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='reviews/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_calculator',
            field=models.BooleanField(default=True, help_text='Если выключено, блок скрыт; кнопка в герое ведёт в каталог. Тексты калькулятора — в «Главная страница (контент)».', verbose_name='Показывать калькулятор на главной'),
        ),
    ]
