# Generated by Django 6.0.4 on 2026-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sitesettings_product_photo_aspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_intro',
            field=models.TextField(blank=True, default='Тенты, навесы и шатры для транспорта, складов, общепита и мероприятий.', help_text='Страница /catalog — абзац под заголовком «Каталог».', verbose_name='Каталог: текст под заголовком'),
        ),
    ]
