# Generated by Django 6.0.4 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_sitesettings_catalog_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_outbound_from',
            field=models.CharField(blank=True, default='', help_text='Например: sales@example.com или «Фабрика Тентов» <sales@example.com>. Пусто — берётся email из блока «Контакты на витрине».', max_length=255, verbose_name='Отправитель писем (From)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_recipients',
            field=models.TextField(blank=True, help_text='Кому слать письма о заявках с калькулятора и из корзины. Несколько адресов — через запятую или с новой строки.', verbose_name='Получатели заявок (email)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='Если выключено, заявки только сохраняются в админке, письма не отправляются.', verbose_name='Включить отправку через SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP сервер'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='Для Яндекс/Google — пароль приложения. Можно не хранить в БД: задайте переменную окружения DJANGO_SMTP_PASSWORD (имеет приоритет).', max_length=255, verbose_name='SMTP пароль'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP порт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='SSL (порт 465)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS (STARTTLS)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP логин'),
        ),
    ]
