# Generated by Django 6.0.4 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sitesettings_smtp_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_outbound_from',
            field=models.CharField(blank=True, default='', help_text='Нужен реальный email. Можно только имя (например «Фабрика Тентов») — тогда к почте из «Контакты на витрине» добавится подпись. Или полностью: «Название» <send@домен.ru>.', max_length=255, verbose_name='Отправитель писем (From)'),
        ),
    ]
