# Generated by Django 6.0.4 on 2026-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sitesettings_from_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('hero', 'Главная (Hero)'), ('other', 'Другое')], db_index=True, default='hero', max_length=32, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка (обратный звонок)',
                'verbose_name_plural': 'Заявки: обратный звонок',
                'ordering': ['-created_at'],
            },
        ),
    ]
