# Generated by Django 6.0.4 on 2026-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_astrum_entity_behavior_create_anyway'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='password_change_deadline',
            field=models.DateTimeField(blank=True, help_text='Заполняется при автосоздании аккаунта из заказа: пароль из письма нужно сменить до этой даты.', null=True, verbose_name='Сменить пароль до'),
        ),
    ]
