# Generated by Django 6.0.4 on 2026-04-13 18:57

from django.db import migrations, models


def add_buyer_order_confirmation_row(apps, schema_editor):
    from api.email_template_defaults import DEFAULT_EMAIL_TEMPLATES

    SiteEmailTemplate = apps.get_model("api", "SiteEmailTemplate")
    key = "buyer_order_confirmation"
    if SiteEmailTemplate.objects.filter(key=key).exists():
        return
    d = DEFAULT_EMAIL_TEMPLATES[key]
    SiteEmailTemplate.objects.create(key=key, subject=d["subject"], body=d["body"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_site_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteemailtemplate',
            name='key',
            field=models.CharField(choices=[('manager_calculator', 'Менеджерам: заявка с калькулятора'), ('manager_callback', 'Менеджерам: обратный звонок'), ('manager_cart', 'Менеджерам: заказ из корзины'), ('buyer_credentials', 'Покупателю: доступ в личный кабинет'), ('buyer_order_confirmation', 'Покупателю: подтверждение заказа'), ('smtp_test', 'Служебное: тест SMTP из админки')], max_length=64, unique=True, verbose_name='Тип письма'),
        ),
        migrations.RunPython(add_buyer_order_confirmation_row, noop_reverse),
    ]
