# Generated by Django 6.0.4 on 2026-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sitesettings_cdek_manual_pvz_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_allow_indexing',
            field=models.BooleanField(default=True, help_text='Выключите на тестовом домене: robots.txt закроет сайт, sitemap опустеет.', verbose_name='SEO: разрешить индексацию (robots, sitemap)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_default_meta_description',
            field=models.TextField(blank=True, default='', help_text='Подставляется на страницах, где нет своего текста (обрезается до ~160 символов в разметке).', max_length=500, verbose_name='SEO: описание сайта по умолчанию (meta description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_site_region',
            field=models.CharField(blank=True, default='RU', help_text='Для schema.org и ориентира поисковиков: RU, Московская область и т.п.', max_length=120, verbose_name='SEO: регион для микроразметки (addressRegion, РФ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title_suffix',
            field=models.CharField(blank=True, default='', help_text='Например короткое имя бренда. Пусто — используется «Название сайта» из шапки.', max_length=120, verbose_name='SEO: суффикс title (через « | »)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_counter_id',
            field=models.CharField(blank=True, default='', help_text='Только цифры, например 12345678. Пусто — скрипт не вставляется.', max_length=32, verbose_name='Яндекс Метрика: номер счётчика'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_metrika_enabled',
            field=models.BooleanField(default=False, help_text='Если включено и задан номер счётчика, на витрине загружается тег Метрики. Вебвизор и карта кликов — в интерфейсе Метрики.', verbose_name='Яндекс Метрика: подключить на сайте'),
        ),
    ]
