# Generated by Django 6.0.4 on 2026-05-02 21:31

from django.db import migrations, models


def _ensure_singleton(apps, schema_editor):
    OzonLogisticsSettings = apps.get_model("ozon_logistics", "OzonLogisticsSettings")
    OzonLogisticsSettings.objects.get_or_create(pk=1, defaults={})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OzonLogisticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', help_text='Заголовок Client-Id. Можно задать через env OZON_LOGISTICS_SELLER_CLIENT_ID — он имеет приоритет.', max_length=64, verbose_name='Client-Id (частное приложение)')),
                ('api_key', models.CharField(blank=True, default='', help_text='Заголовок Api-Key. Env: OZON_LOGISTICS_SELLER_API_KEY (приоритет над полем).', max_length=512, verbose_name='Api-Key')),
                ('seller_api_base_url', models.CharField(blank=True, default='', help_text='Пусто — https://api-seller.ozon.ru. Env: OZON_LOGISTICS_SELLER_API_URL.', max_length=200, verbose_name='Базовый URL Seller API')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Не используются в API; для команды.', verbose_name='Внутренние заметки')),
            ],
            options={
                'verbose_name': 'Настройки Ozon Доставка (Seller API)',
                'verbose_name_plural': 'Настройки Ozon Доставка (Seller API)',
            },
        ),
        migrations.RunPython(_ensure_singleton, migrations.RunPython.noop),
    ]
