# Generated by Django 6.0.4 on 2026-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonlogisticssettings',
            name='internal_phones_allowlist',
            field=models.TextField(blank=True, default='', help_text='Один номер в строке или через запятую. Форматы: 79001234567, +7 900 123-45-67, 9001234567. Учитывается только при включённой опции выше.', verbose_name='Список разрешённых телефонов для создания заказа в Ozon'),
        ),
        migrations.AddField(
            model_name='ozonlogisticssettings',
            name='order_create_only_internal_phones',
            field=models.BooleanField(default=False, help_text='Если включено — перед вызовом /v2/order/create проверяется телефон покупателя по списку ниже; иначе запрос не уходит в Ozon (защита от случайной реальной отгрузки на проде). Рекомендуется включить на проде, пока идёт тестирование.', verbose_name='Создание заказа в Ozon: только «внутренние» телефоны'),
        ),
        migrations.AddField(
            model_name='ozonlogisticssettings',
            name='seller_delivery_api_enabled',
            field=models.BooleanField(default=False, help_text='Пока выключено — сайт и оплата работают по прежней схеме в «api». Когда включите и доработаете вызовы checkout → order_create из приложения ozon_logistics, можно постепенно переключать ветки кода на эти методы, не отключая старый поток до готовности.', verbose_name='Использовать Seller API Ozon Доставка (новый поток)'),
        ),
    ]
