/**
 * Человекочитаемые подписи полей Staff API (camelCase) для динамических форм.
 * Если ключа нет — см. fallback в конце файла.
 */

/** Превью в imageUrls (главная страница) */
export const STAFF_HOME_IMAGE_URL_LABELS: Record<string, string> = {
  heroBackgroundUrl: 'Фон первого экрана (Hero)',
  ps0IconImageUrl: 'Карточка 1 — своя картинка',
  ps1IconImageUrl: 'Карточка 2 — своя картинка',
  ps2IconImageUrl: 'Карточка 3 — своя картинка',
  ps3IconImageUrl: 'Карточка 4 — своя картинка',
}

/** Модельное поле файла → PATCH-ключ и ключ в imageUrls */
export const STAFF_HOME_MODEL_IMAGE: Record<
  string,
  { patchKey: string; urlKey: keyof typeof STAFF_HOME_IMAGE_URL_LABELS }
> = {
  heroBackground: { patchKey: 'heroBackgroundRelativePath', urlKey: 'heroBackgroundUrl' },
  ps0IconImage: { patchKey: 'ps0IconImageRelativePath', urlKey: 'ps0IconImageUrl' },
  ps1IconImage: { patchKey: 'ps1IconImageRelativePath', urlKey: 'ps1IconImageUrl' },
  ps2IconImage: { patchKey: 'ps2IconImageRelativePath', urlKey: 'ps2IconImageUrl' },
  ps3IconImage: { patchKey: 'ps3IconImageRelativePath', urlKey: 'ps3IconImageUrl' },
}

/** Подписи для загрузки картинок главной (модельное имя поля) */
export const STAFF_HOME_MODEL_IMAGE_LABELS: Record<string, string> = {
  heroBackground: 'Фон первого экрана (Hero)',
  ps0IconImage: 'Карточка «Проблема — решение» 1 — картинка вместо иконки',
  ps1IconImage: 'Карточка 2 — картинка',
  ps2IconImage: 'Карточка 3 — картинка',
  ps3IconImage: 'Карточка 4 — картинка',
}

const HOME_LABELS: Record<string, string> = {
  metaTitle: 'SEO: заголовок страницы (title)',
  metaDescription: 'SEO: описание (meta description)',
  metaOrgName: 'Микроразметка: название организации',
  metaOrgDescription: 'Микроразметка: описание организации',
  heroTitle: 'Заголовок Hero',
  heroSubtitle: 'Подзаголовок Hero',
  heroCtaPrimary: 'Текст основной кнопки',
  heroPrimaryAction: 'Подпись действия основной кнопки',
  heroPrimaryHref: 'Ссылка основной кнопки',
  heroCtaSecondary: 'Текст второй кнопки',
  heroSecondaryAction: 'Подпись второй кнопки',
  heroSecondaryHref: 'Ссылка второй кнопки',
  heroCbTitle: 'Заголовок формы обратного звонка',
  heroCbNameLabel: 'Подпись поля «Имя»',
  heroCbPhoneLabel: 'Подпись поля «Телефон»',
  heroCbSubmit: 'Текст кнопки отправки',
  heroCbSubmitting: 'Текст при отправке',
  heroCbSuccess: 'Сообщение после успешной отправки',
  psHeading: 'Заголовок блока',
  psSubheading: 'Подзаголовок блока',
  ps0Problem: 'Карточка 1: формулировка проблемы',
  ps0Solution: 'Карточка 1: решение',
  ps0IconKind: 'Карточка 1: тип иконки',
  ps0Icon: 'Карточка 1: иконка (preset)',
  ps0FaPreset: 'Карточка 1: Font Awesome preset',
  ps0Fontawesome: 'Карточка 1: класс Font Awesome',
  ps1Problem: 'Карточка 2: проблема',
  ps1Solution: 'Карточка 2: решение',
  ps1IconKind: 'Карточка 2: тип иконки',
  ps1Icon: 'Карточка 2: иконка',
  ps1FaPreset: 'Карточка 2: FA preset',
  ps1Fontawesome: 'Карточка 2: Font Awesome',
  ps2Problem: 'Карточка 3: проблема',
  ps2Solution: 'Карточка 3: решение',
  ps2IconKind: 'Карточка 3: тип иконки',
  ps2Icon: 'Карточка 3: иконка',
  ps2FaPreset: 'Карточка 3: FA preset',
  ps2Fontawesome: 'Карточка 3: Font Awesome',
  ps3Problem: 'Карточка 4: проблема',
  ps3Solution: 'Карточка 4: решение',
  ps3IconKind: 'Карточка 4: тип иконки',
  ps3Icon: 'Карточка 4: иконка',
  ps3FaPreset: 'Карточка 4: FA preset',
  ps3Fontawesome: 'Карточка 4: Font Awesome',
  ttHeading: 'Заголовок блока «Виды тентов»',
  ttSubheading: 'Подзаголовок',
  featHeading: 'Заголовок подборки',
  featSubheading: 'Подзаголовок',
  featCatalogCta: 'Текст ссылки в каталог',
  calcHeading: 'Заголовок калькулятора',
  calcSubheading: 'Подзаголовок',
  calcLengthLabel: 'Подпись поля «Длина»',
  calcWidthLabel: 'Подпись поля «Ширина»',
  calcMaterialLabel: 'Подпись «Материал»',
  calcOptionsLabel: 'Подпись «Опции»',
  calcEstimateLabel: 'Подпись к оценке',
  calcEstimateNote: 'Примечание к оценке',
  calcNameLabel: 'Подпись «Имя»',
  calcPhoneLabel: 'Подпись «Телефон»',
  calcCommentLabel: 'Подпись «Комментарий»',
  calcNamePlaceholder: 'Плейсхолдер имени',
  calcPhonePlaceholder: 'Плейсхолдер телефона',
  calcCommentPlaceholder: 'Плейсхолдер комментария',
  calcSubmitButton: 'Текст кнопки отправки',
  calcSubmitting: 'Текст при отправке',
  calcSuccessMessage: 'Сообщение после успешной отправки',
  portHeading: 'Заголовок портфолио',
  portSubheading: 'Подзаголовок',
  portFilters: 'Текст фильтров',
  portLoading: 'Текст загрузки',
  portEmpty: 'Текст «нет работ»',
  portAllCta: 'Ссылка «Все работы»',
  whyHeading: 'Заголовок «Почему мы»',
  whySubheading: 'Подзаголовок',
  whyS0Value: 'Счётчик 1: значение',
  whyS0Suffix: 'Счётчик 1: суффикс',
  whyS0Label: 'Счётчик 1: подпись',
  whyS1Value: 'Счётчик 2: значение',
  whyS1Suffix: 'Счётчик 2: суффикс',
  whyS1Label: 'Счётчик 2: подпись',
  whyS2Value: 'Счётчик 3: значение',
  whyS2Suffix: 'Счётчик 3: суффикс',
  whyS2Label: 'Счётчик 3: подпись',
  whyC0Title: 'Колонка 1: заголовок',
  whyC0Text: 'Колонка 1: текст',
  whyC0Icon: 'Колонка 1: иконка',
  whyC1Title: 'Колонка 2: заголовок',
  whyC1Text: 'Колонка 2: текст',
  whyC1Icon: 'Колонка 2: иконка',
  whyC2Title: 'Колонка 3: заголовок',
  whyC2Text: 'Колонка 3: текст',
  whyC2Icon: 'Колонка 3: иконка',
  whyC3Title: 'Колонка 4: заголовок',
  whyC3Text: 'Колонка 4: текст',
  whyC3Icon: 'Колонка 4: иконка',
  revHeading: 'Заголовок отзывов',
  revSubheading: 'Подзаголовок',
  revLoading: 'Текст загрузки',
  revVideoCaption: 'Подпись к видео',
  blogHeading: 'Заголовок блока блога',
  blogSubheading: 'Подзаголовок',
  blogAllLink: 'Текст ссылки «Все статьи»',
  blogReadMore: 'Текст «Читать далее»',
  blogLoading: 'Текст загрузки',
  mapHeading: 'Заголовок карты',
  mapSubheading: 'Подзаголовок',
  mapIframeSrc: 'URL iframe карты',
  mapTitle: 'Атрибут title у iframe',
  mapFormNameLabel: 'Подпись поля «Имя»',
  mapFormPhoneLabel: 'Подпись «Телефон»',
  mapFormCommentLabel: 'Подпись «Комментарий»',
  mapNamePlaceholder: 'Плейсхолдер имени',
  mapPhonePlaceholder: 'Плейсхолдера телефона',
  mapCommentPlaceholder: 'Плейсхолдер комментария',
  mapSubmitButton: 'Текст кнопки отправки',
  uiLoadingFeatured: 'Текст загрузки подборки',
  uiBuyMarketplaces: 'Текст блока маркетплейсов (десктоп)',
  uiBuyMarketplacesMobile: 'Текст блока маркетплейсов (мобильный)',
}

/** Настройки сайта (SiteSettings) — camelCase как в API */
const SITE_LABELS: Record<string, string> = {
  logo: 'Логотип (текущий файл)',
  favicon: 'Фавикон (текущий файл)',
  siteName: 'Название сайта',
  siteTagline: 'Слоган в подвале',
  footerNote: 'Короткий текст под слоганом',
  showMarketplaceWb: 'Показывать ссылку на Wildberries',
  showMarketplaceOzon: 'Показывать ссылку на Ozon',
  showMarketplaceYm: 'Показывать ссылку на Яндекс Маркет',
  showMarketplaceAvito: 'Показывать ссылку на Авито',
  showCalculator: 'Показывать блок калькулятора на главной',
  productPhotoAspect: 'Формат фото товаров в каталоге',
  catalogIntro: 'Каталог: текст под заголовком',
  globalUrlWb: 'Ссылка на витрину Wildberries',
  globalUrlOzon: 'Ссылка на витрину Ozon',
  globalUrlYm: 'Ссылка на Яндекс Маркет',
  globalUrlAvito: 'Ссылка на Авито',
  phoneDisplay: 'Телефон (как отображается)',
  phoneHref: 'Ссылка для звонка (tel:…)',
  email: 'Email для связи',
  address: 'Адрес (текст)',
  legal: 'Реквизиты (кратко)',
  footerVkUrl: 'Ссылка ВКонтакте',
  footerTelegramUrl: 'Ссылка Telegram',
  showSocialLinks: 'Показывать блок «Соцсети» в подвале',
  contactsPageTitle: 'Страница «Контакты»: заголовок',
  contactsIntro: 'Страница «Контакты»: вводный текст',
  contactsHours: 'Режим работы',
  contactsMetaDescription: 'Страница «Контакты»: meta description',
  contactsBackLinkLabel: 'Текст ссылки «Назад на главную»',
  mapHeading: 'Блок карты на главной: заголовок',
  mapSubheading: 'Блок карты: подзаголовок',
  mapIframeSrc: 'Карта: URL iframe',
  mapTitle: 'Карта: title у iframe',
  mapFormNameLabel: 'Форма: подпись «Имя»',
  mapFormPhoneLabel: 'Форма: подпись «Телефон»',
  mapFormCommentLabel: 'Форма: подпись «Комментарий»',
  mapNamePlaceholder: 'Плейсхолдер имени',
  mapPhonePlaceholder: 'Плейсхолдер телефона',
  mapCommentPlaceholder: 'Плейсхолдер комментария',
  mapSubmitButton: 'Текст кнопки отправки',
  mapSubmitting: 'Текст при отправке',
  mapSuccessMessage: 'Сообщение после успешной отправки',
  notificationRecipients: 'Кому слать письма о заявках',
  smtpEnabled: 'Включить отправку писем через SMTP',
  smtpHost: 'SMTP сервер',
  smtpPort: 'SMTP порт',
  smtpUseTls: 'TLS (STARTTLS)',
  smtpUseSsl: 'SSL (порт 465)',
  smtpUser: 'SMTP логин',
  smtpPassword: 'SMTP пароль (сохранён)',
  emailOutboundFrom: 'Отправитель писем (From)',
  astrumCrmEnabled: 'Отправлять заказы в Битрикс24 (Astrum)',
  astrumCrmApiKey: 'API-ключ Astrum',
  astrumCrmAssignedDefault: 'ID ответственного в Битрикс24',
  astrumCrmApiUrl: 'URL endpoint заказа Astrum',
  astrumCrmContactBehavior: 'Поведение с контактами',
  astrumCrmEntityBehavior: 'Поведение со сделкой/лидом',
  astrumCrmDealTitlePrefix: 'Префикс названия сделки',
  astrumCrmTimeoutSeconds: 'Таймаут HTTP (сек)',
  bitrix24WebhookBase: 'База URL вебхука REST Битрикс24',
  bitrix24CatalogProductIblockId: 'ID инфоблока товаров',
  bitrix24CatalogOfferIblockId: 'ID инфоблока предложений',
  checkoutPickupEnabled: 'Самовывоз: показывать на сайте',
  pickupPointTitle: 'Самовывоз: название точки',
  pickupPointAddress: 'Самовывоз: адрес',
  pickupPointHours: 'Самовывоз: режим выдачи',
  pickupPointNote: 'Самовывоз: как проехать / комментарий',
  pickupPointLat: 'Самовывоз: широта',
  pickupPointLng: 'Самовывоз: долгота',
  cdekEnabled: 'СДЭК: включить на сайте',
  cdekTestMode: 'СДЭК: тестовый контур',
  cdekAccount: 'СДЭК: Account',
  cdekSecurePassword: 'СДЭК: пароль (сохранён)',
  cdekWidgetScriptUrl: 'СДЭК: URL скрипта виджета',
  cdekYandexMapApiKey: 'СДЭК: ключ Яндекс.Карт',
  cdekWidgetSenderCity: 'СДЭК: город отправления',
  cdekManualPvzEnabled: 'СДЭК: ручной ввод ПВЗ',
  ozonLogisticsEnabled: 'Доставка Ozon: показывать способ',
  ozonLogisticsBuyerNote: 'Доставка Ozon: текст для покупателя',
  ozonPayEnabled: 'Ozon Pay: включить оплату',
  ozonPaySandbox: 'Ozon Pay: песочница',
  ozonPayClientId: 'Ozon Pay: Client ID',
  ozonPayClientSecret: 'Ozon Pay: секрет (сохранён)',
  ozonPayWebhookSecret: 'Ozon Pay: секрет вебхука (сохранён)',
  yandexMetrikaEnabled: 'Яндекс.Метрика: включить',
  yandexMetrikaCounterId: 'Яндекс.Метрика: номер счётчика',
  seoAllowIndexing: 'Разрешить индексацию (robots)',
  seoSiteRegion: 'Регион сайта (SEO)',
  seoDefaultMetaDescription: 'Описание сайта по умолчанию (SEO)',
  seoTitleSuffix: 'Суффикс заголовка страниц',
  logoRelativePath: 'Новый логотип (загрузка)',
  faviconRelativePath: 'Новый фавикон (загрузка)',
  smtpPasswordNew: 'Новый SMTP пароль',
  astrumCrmApiKeyNew: 'Новый API-ключ Astrum',
  cdekSecurePasswordNew: 'Новый пароль СДЭК',
  ozonPayClientSecretNew: 'Новый секрет Ozon Pay',
  ozonPayWebhookSecretNew: 'Новый секрет вебхука',
  bitrix24WebhookBaseNew: 'Новая база URL вебхука',
}

export function homeFieldLabelRu(key: string): string {
  return HOME_LABELS[key] ?? prettifyCamelFallback(key)
}

export function siteSettingsFieldLabelRu(key: string): string {
  return SITE_LABELS[key] ?? prettifyCamelFallback(key)
}

function prettifyCamelFallback(key: string): string {
  const spaced = key
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .trim()
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}
